### PR TITLE
Project file generation with xcodegen

### PR DESCRIPTION
**Pull request by phloux**
#391

### CODE REVIEW

**Comment by yostyle** [comment]
Procedure to test it from version before the rebase :
$ brew install xcodegen
$ xcodegen
$ pod repo remove trunk
$ pod install --repo-update
$ open Tchap.xcworkspace

**Review by yostyle — CHANGES_REQUESTED** [review]
I can build both target Tchap and Btchap
I can't login on Btchap. I have the following stacktrace :
```
2021-09-09 17:22:45.671065+0200 Btchap[41786:5239587]  [MXHTTPClient] #23 - GET info
2021-09-09 17:22:45.671476+0200 Btchap[41786:5239587]  [MXBackgroundTask] Start background task #25 - [MXHTTPClient] startBackgroundTask
2021-09-09 17:22:45.672218+0200 Btchap[41786:5239587]  [MXBackgroundTask] Background task [MXHTTPClient] startBackgroundTask started with app state: active and estimated background time remaining: undetermined
2021-09-09 17:22:45.769249+0200 Btchap[41786:5259363]  [MXHTTPClient] Shall we trust matrix.i.tchap.gouv.fr?
2021-09-09 17:22:45.769455+0200 Btchap[41786:5259363]  [MXHTTPClient] No, the user doesn't trust it
2021-09-09 17:22:45.770116+0200 Btchap[41786:5239587]  [MXHTTPClient] #23 - GET info completed in 99ms
2021-09-09 17:22:45.770442+0200 Btchap[41786:5239587]  [MXHTTPClient] Request 0x6000014ff580 failed for path: info - HTTP code: 0. Error: Error Domain=NSURLErrorDomain Code=-999 "annulé" UserInfo={NSErrorFailingURLStringKey=https://matrix.i.tchap.gouv.fr/_matrix/identity/api/v1/info?address=***************&medium=email, NSErrorFailingURLKey=https://matrix.i.tchap.gouv.fr/_matrix/identity/api/v1/info?address=***************&medium=email, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <0999F49D-3D38-4378-8F83-7C6E77E62DEB>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <0999F49D-3D38-4378-8F83-7C6E77E62DEB>.<1>, NSLocalizedDescription=annulé}
2021-09-09 17:22:45.770702+0200 Btchap[41786:5239587]  [ThirdPartyIDPlatformInfoResolver] info resquest on https://matrix.i.tchap.gouv.fr failed
2021-09-09 17:22:45.798294+0200 Btchap[41786:5239587]  [MXHTTPClient] #24 - GET info
2021-09-09 17:22:45.798701+0200 Btchap[41786:5239587]  [MXBackgroundTask] Start background task #26 - [MXHTTPClient] startBackgroundTask
2021-09-09 17:22:45.799205+0200 Btchap[41786:5239587]  [MXBackgroundTask] Background task [MXHTTPClient] startBackgroundTask started with app state: active and estimated background time remaining: undetermined
2021-09-09 17:22:45.799651+0200 Btchap[41786:5239587]  [MXHTTPClient] cleanupBackgroundTask
2021-09-09 17:22:45.799970+0200 Btchap[41786:5239587]  [MXBackgroundTask] Stop background task #25 - [MXHTTPClient] startBackgroundTask after 128.631ms
2021-09-09 17:22:45.800372+0200 Btchap[41786:5239587]  [MXHTTPClient] cancel
2021-09-09 17:22:45.800676+0200 Btchap[41786:5239587]  [MXHTTPClient] cleanupBackgroundTask
2021-09-09 17:22:45.800904+0200 Btchap[41786:5259501]  [MXHTTPClient] SessionDidBecomeInvalid: <__NSURLSessionLocal: 0x7f9d17e20270>: (null)
2021-09-09 17:22:45.801120+0200 Btchap[41786:5259501] ⚠️ [MXStrongifyAndReturnIfNil] Released reference at MXHTTPClient.m:147
2021-09-09 17:22:45.894751+0200 Btchap[41786:5253618]  [MXHTTPClient] Shall we trust matrix.e.tchap.gouv.fr?
2021-09-09 17:22:45.894949+0200 Btchap[41786:5253618]  [MXHTTPClient] No, the user doesn't trust it
2021-09-09 17:22:45.895656+0200 Btchap[41786:5239587]  [MXHTTPClient] #24 - GET info completed in 97ms
2021-09-09 17:22:45.896063+0200 Btchap[41786:5239587]  [MXHTTPClient] Request 0x6000014988c0 failed for path: info - HTTP code: 0. Error: Error Domain=NSURLErrorDomain Code=-999 "annulé" UserInfo={NSErrorFailingURLStringKey=https://matrix.e.tchap.gouv.fr/_matrix/identity/api/v1/info?address=***************&medium=email, NSErrorFailingURLKey=https://matrix.e.tchap.gouv.fr/_matrix/identity/api/v1/info?address=***************&medium=email, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <A3A31D93-4F81-40A0-A3B7-4D460B240B93>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <A3A31D93-4F81-40A0-A3B7-4D460B240B93>.<1>, NSLocalizedDescription=annulé}
2021-09-09 17:22:45.896340+0200 Btchap[41786:5239587]  [ThirdPartyIDPlatformInfoResolver] info resquest on https://matrix.e.tchap.gouv.fr failed
2021-09-09 17:22:45.922062+0200 Btchap[41786:5239587]  [MXHTTPClient] cleanupBackgroundTask
2021-09-09 17:22:45.922465+0200 Btchap[41786:5239587]  [MXBackgroundTask] Stop background task #26 - [MXHTTPClient] startBackgroundTask after 123.851ms
2021-09-09 17:22:45.922872+0200 Btchap[41786:5239587]  [MXHTTPClient] cancel
2021-09-09 17:22:45.923106+0200 Btchap[41786:5239587]  [MXHTTPClient] cleanupBackgroundTask
2021-09-09 17:22:45.923297+0200 Btchap[41786:5259501]  [MXHTTPClient] SessionDidBecomeInvalid: <__NSURLSessionLocal: 0x7f9d37d487c0>: (null)
2021-09-09 17:22:45.923521+0200 Btchap[41786:5259501] ⚠️ [MXStrongifyAndReturnIfNil] Released reference at MXHTTPClient.m:147
```
On Tchap the app crashed after the login process. I have the following stacktrace :
```
2021-09-09 17:33:15.573029+0200 Tchap[43184:5270877] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'MXKLanguageBundle </Users/yostyle/Library/Developer/CoreSimulator/Devices/955982C7-344C-4FB5-B4EB-804F895AD873/data/Containers/Bundle/Application/D790D328-5C21-498A-B655-BFDC59833DEC/Tchap.app> (loaded)' with name 'RecentsViewController''
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20422e98 -[NSException initWithCoder:] + 0
	3   UIKitCore                           0x00007fff242b77e0 -[UINib instantiateWithOwner:options:] + 495
	4   MatrixKit                           0x0000000106a74020 -[MXKRecentListViewController viewDidLoad] + 208
	5   Tchap                               0x0000000102368a66 -[RecentsViewController viewDidLoad] + 54
	6   Tchap                               0x000000010240e163 -[RoomsViewController viewDidLoad] + 51
	7   UIKitCore                           0x00007fff23f806a9 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 88
	8   UIKitCore                           0x00007fff23f8504c -[UIViewController loadViewIfRequired] + 1084
	9   UIKitCore                           0x00007fff23f85436 -[UIViewController view] + 27
	10  Tchap                               0x0000000102411e33 -[SegmentedViewController displaySelectedViewController] + 1683
	11  Tchap                               0x0000000102411195 -[SegmentedViewController createSegmentedViews] + 2229
	12  Tchap                               0x0000000102410141 -[SegmentedViewController viewDidLoad] + 1233
	13  UIKitCore                           0x00007fff23f806a9 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 88
	14  UIKitCore                           0x00007fff23f8504c -[UIViewController loadViewIfRequired] + 1084
	15  UIKitCore                           0x00007fff23f85436 -[UIViewController view] + 27
	16  Tchap                               0x0000000102897376 $sSo16UIViewControllerC5TchapE015vc_addChildViewB004viewB002onG0yAB_So0A0CtF + 150
	17  Tchap                               0x00000001025dcb97 $s5Tchap18HomeViewControllerC014setupSegmentedcD033_2A15F1210E3A17517EC0C814ECAF1070LLyyF + 1367
	18  Tchap                               0x00000001025dc1b9 $s5Tchap18HomeViewControllerC11viewDidLoadyyF + 121
	19  Tchap                               0x00000001025dcdcb $s5Tchap18HomeViewControllerC11viewDidLoadyyFTo + 43
	20  UIKitCore                           0x00007fff23f806a9 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 88
	21  UIKitCore                           0x00007fff23f8504c -[UIViewController loadViewIfRequired] + 1084
	22  UIKitCore                           0x00007fff23eba03a -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 162
	23  UIKitCore                           0x00007fff23eba326 -[UINavigationController _startTransition:fromViewController:toViewController:] + 154
	24  UIKitCore                           0x00007fff23ebb3b8 -[UINavigationController _startDeferredTransitionIfNeeded:] + 876
	25  UIKitCore                           0x00007fff23ebc734 -[UINavigationController __viewWillLayoutSubviews] + 150
	26  UIKitCore                           0x00007fff23e9d04c -[UILayoutContainerView layoutSubviews] + 217
	27  UIKitCore                           0x00007fff24c18c90 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2946
	28  QuartzCore                          0x00007fff27a055b8 -[CALayer layoutSublayers] + 258
	29  QuartzCore                          0x00007fff27a0be3f _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 611
	30  QuartzCore                          0x00007fff27a17c53 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
	31  QuartzCore                          0x00007fff27951f26 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 656
	32  QuartzCore                          0x00007fff279893b9 _ZN2CA11Transaction6commitEv + 713
	33  QuartzCore                          0x00007fff2798a51f _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 79
	34  CoreFoundation                      0x00007fff2038fd31 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	35  CoreFoundation                      0x00007fff2038a542 __CFRunLoopDoObservers + 541
	36  CoreFoundation                      0x00007fff2038aaf5 __CFRunLoopRun + 1129
	37  CoreFoundation                      0x00007fff2038a1a7 CFRunLoopRunSpecific + 567
	38  GraphicsServices                    0x00007fff2b874d85 GSEventRunModal + 139
	39  UIKitCore                           0x00007fff246c14df -[UIApplication _run] + 912
	40  UIKitCore                           0x00007fff246c639c UIApplicationMain + 101
	41  Tchap                               0x0000000102464b2b main + 75
	42  libdyld.dylib                       0x00007fff2025abbd start + 1
	43  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'MXKLanguageBundle </Users/yostyle/Library/Developer/CoreSimulator/Devices/955982C7-344C-4FB5-B4EB-804F895AD873/data/Containers/Bundle/Application/D790D328-5C21-498A-B655-BFDC59833DEC/Tchap.app> (loaded)' with name 'RecentsViewController''
```

**Comment by giomfo** [comment]
I reproduce the same error on Tchap
The todo list is:

- [ ] remove the Siri extension from the Tchap project (Let the SiriIntent like we get it from Element-iOS, delete BSiriIntent (I think you created it)
- [ ] fix the exception "NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'MXKLanguageBundle..." on Tchap target
- [ ] fix login on Btchap

**Review by yostyle — CHANGES_REQUESTED** [review]
We have ressource id instead of value on screen.

**Review by yostyle — APPROVED** [review]
LGTM

**Comment by yostyle** [comment]
LGTM
Last commits reviewed with @phlniji

**Pull request merged**
