### PR TITLE
Hide menu for invited users

### PR DESCRIPTION
**Pull request by phlniji**
https://github.com/tchapgouv/tchap-ios/issues/701#issuecomment-1372245418

### CODE REVIEW

**Comment by giomfo** [comment]
@phlniji your change is ok
but I did some tests, and I discovered a bug:
- the plus button is not correctly updated after a new login :
   - If I log in with an agent account after log out an external account the (+) is missing
   - if I log in with an external account after logging out an agent account: the (+) is visible with the 3 options

I think you need to update this (+) button on `userSessionsServiceDidAddUserSession` like you already did for the top left button

**Comment by phlniji** [comment]
> @phlniji your change is ok but I did some tests, and I discovered a bug:
> 
> * the plus button is not correctly updated after a new login :
>   
>   * If I log in with an agent account after log out an external account the (+) is missing
>   * if I log in with an external account after logging out an agent account: the (+) is visible with the 3 options
> 
> I think you need to update this (+) button on `userSessionsServiceDidAddUserSession` like you already did for the top left button

We already observe the `UserSessionsService.didAddUserSession` notification. 
So I think the notification registration has been done too late, or there is an issue with the `guard isViewLoaded` from `updateUI` method.
I will check this.

**Review by giomfo — APPROVED** [review]
LGTM
As we discussed it in direct, I let you have a look on the use case highlighted above. Because the probability for an actual user to observe it is very low, we will manage it only if a simple fix is possible

**Review by giomfo — APPROVED** [review]
LGTM

**Pull request merged**
